version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zk1
    ports:
      - "2181:2181"
    hostname: zk1
    networks:
      - kafka-spark
    tty: true

  kafka:
    image: wurstmeister/kafka
    container_name: kafka1
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.12
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181
      KAFKA_CREATE_TOPICS: "flumeTopic:1:1"
    volumes:
      - ./volume/kafka/run/docker.sock:/var/run/docker.sock
    hostname: kafka1
    networks:
      - kafka-spark
    tty: true    

  flume:
    image: myflume
    container_name: flume1
    depends_on: [kafka]
    ports:
      - "40000:40000"
    hostname: flume1
    networks:
      - kafka-spark
    tty: true

networks:
  kafka-spark: